version: "3"
services:
  api:
    build:
      context: ./api
      dockerfile: dockerfile  
    ports:
      - "8080:8080"  
    environment:
      - NODE_ENV=development  
      - PG_HOST=host.docker.internal
    depends_on:
      - database
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Porta do host : Porta do contêiner
    environment:
      - REACT_APP_API_URL=http://host.docker.internal:8080

  database:
    container_name: postgres-db
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=findajob
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"