version: "3.9"

services:
  postgres:
    container_name: postgres-db
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=findajob
    volumes:
      - ./init:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"