version: '3'
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile  
    ports:
      - "8080:8080"  
    environment:
      - NODE_ENV=development  
      - PG_HOST=host.docker.internal
    env_file:
      - .env 